# Generated by Django 3.2.6 on 2021-08-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="User1", max_length=255),
            preserve_default=False,
        ),
    ]
