version: '3'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  frontend:
    image: kalacey412/todolist_frontend:latest  
    restart: unless-stopped
    ports:
        - 80:80
    volumes:
        - ./frontend/nginx:/etc/nginx/conf.d
    depends_on: 
        - backend
  backend:
    image: kalacey412/todolist_backend:latest  
    restart: unless-stopped
    env_file:
      - ./backend/.env
    command: gunicorn config.wsgi --bind 0.0.0.0:8000
    
    expose:
      - 8000
    depends_on:
      - db
volumes:
  postgres_data:
      